### PR TITLE
Update SDE with DLT-viewer

### PR DESCRIPTION
**Pull request by pancio88**

### CODE REVIEW

**Comment by pancio88** [comment]
@rpannek is ok if I add to the pull request also your commits? Or I should add just my commits related to the DLT viewer? Should I add someone else to this code review?

**Comment by rpannek** [comment]
The first two ones are already in, so you should remove them, the merge commits should also be removed. And the labels in the Jenkinsfile are project specific too, so that should be removed also. Basically only your two commits make sense in this context I think.

**Comment by pancio88** [comment]
Got it

**Comment by rpannek** [comment]
You shouldn't close this pull request, you should just adjust your commits in it. To do that change it in your local repo and force push it to your fork here on GitHub, this will update this pull request with the changes. Please reopen this PR.

**Pull request closed without merging**
