### PR TITLE
Vagrantfile: switch to Ubuntu 18.04

### PR DESCRIPTION
**Pull request by sashko**
Signed-off-by: Oleksandr Kravchuk <oleksandr.kravchuk@pelagicore.com>

### CODE REVIEW

**Review by DunderRoffe — APPROVED** [review]

**Comment by DunderRoffe** [comment]
A suggestion is to use LXDE or something smaller than gnome-desktop.
I get that this is just updating what was already there,  but when it's changing it might be nice to install something smaller to reduce build times :)

**Comment by sashko** [comment]
@DunderRoffe that's not a bad idea. Let me try LXCD instead...

**Comment by rpannek** [comment]
But will people want to use LXCD instead of gnome?

**Comment by sashko** [comment]
@rpannek how dare you!

**Comment by sashko** [comment]
I'm gonna go ahead and merge this. We'll consider other DEs.

**Pull request merged**
